# Generated by Django 3.0.2 on 2024-02-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('identifiant', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prediction', models.DateField(auto_now_add=True)),
                ('rendement_predit', models.FloatField()),
                ('prix_predit', models.FloatField()),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgriApp.Agriculteur')),
            ],
        ),
        migrations.CreateModel(
            name='InformationAgricole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.FloatField()),
                ('region', models.CharField(max_length=100)),
                ('capital', models.FloatField()),
                ('humidite', models.FloatField()),
                ('temperature', models.FloatField()),
                ('qualite_sol', models.CharField(max_length=100)),
                ('rendement', models.FloatField()),
                ('produit', models.CharField(max_length=100)),
                ('prix_produit', models.FloatField()),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgriApp.Agriculteur')),
            ],
        ),
    ]
